// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbhlxnccpplribvasouw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiaGx4bmNjcHBscmlidmFzb3V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMDE0ODQsImV4cCI6MjA1Nzc3NzQ4NH0.wCXKbOkQXnvMwqVy9uO5EsIBhBFttHsnIi--bV3SrK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);